version: "3.9"
services:
  nextcloud:
    image: nextcloudfull
    environment:
      OBJECTSTORE_S3_HOST: #{nextcloud_minio_url}
      OBJECTSTORE_S3_BUCKET: nextcloud
      OBJECTSTORE_S3_KEY: #{minio_access_key}
      OBJECTSTORE_S3_SECRET: #{minio_secret_key} 
      OBJECTSTORE_S3_PORT: #{minio_port}
      OBJECTSTORE_S3_SSL: false
      # OBJECTSTORE_S3_REGION: The region that the S3 bucket resides in.
      OBJECTSTORE_S3_USEPATH_STYLE: true
      # OBJECTSTORE_S3_LEGACYAUTH (default: false): Not required for AWS S3
      # OBJECTSTORE_S3_OBJECT_PREFIX (default: urn:oid:): Prefix to prepend to the fileid
      OBJECTSTORE_S3_AUTOCREATE: true
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: myadminpassword123

    volumes:
      - './nextcloud:/var/www/html'
    ports:
      -  #{nextcloud_port}:80
