version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2022-12-07T00-56-37Z
    environment:
      - MINIO_ACCESS_KEY=#{minio_access_key}
      - MINIO_SECRET_KEY=#{minio_secret_key}
      - MINIO_ROOT_USER=#{minio_root_user}
      - MINIO_ROOT_PASSWORD=#{minio_root_password}
    ports:
      -  #{minio_port}:9000
      -  #{minio_console_port}:#{minio_console_port}
    command: server /data --console-address ":#{minio_console_port}"
